resolver: lts-22.0
packages:
- '.'

extra-deps:
  - github: composewell/streamly
    commit: '04d6fcd39be10d494eb901bff1a6bd973daf0a1b'
    subdirs:
      - core
  - github: composewell/streamly
    commit: '04d6fcd39be10d494eb901bff1a6bd973daf0a1b'

#allow-newer: true
rebuild-ghc-options: true

# Look at https://stackoverflow.com/questions/70045586/could-not-find-module-system-console-mintty-win32-when-compiling-test-framework
flags:
  mintty:
    Win32-2-13-1: false
