resolver: lts-22.0
packages:
- '.'

extra-deps:
  - github: composewell/streamly
    commit: '4aa7ae215f64cf98f7b3c175d3a8c47c8bd3177e'
    subdirs:
      - core
  - github: composewell/streamly
    commit: '4aa7ae215f64cf98f7b3c175d3a8c47c8bd3177e'

#allow-newer: true
rebuild-ghc-options: true

# Look at https://stackoverflow.com/questions/70045586/could-not-find-module-system-console-mintty-win32-when-compiling-test-framework
flags:
  mintty:
    Win32-2-13-1: false
