resolver: lts-22.0
packages:
- '.'

extra-deps:
  - github: composewell/streamly
    commit: '4c0d82e6eb9565483a4fe6f9129e1f4c234b34f1'
    subdirs:
      - core

#allow-newer: true
rebuild-ghc-options: true

# Look at https://stackoverflow.com/questions/70045586/could-not-find-module-system-console-mintty-win32-when-compiling-test-framework
flags:
  mintty:
    Win32-2-13-1: false
