resolver: lts-22.0
packages:
- '.'

extra-deps:
  - github: composewell/streamly
    commit: 'b789e0143c0d3f94aab9793117df021ce421df26'
    subdirs:
      - core
  - github: composewell/streamly
    commit: 'b789e0143c0d3f94aab9793117df021ce421df26'

#allow-newer: true
rebuild-ghc-options: true

# Look at https://stackoverflow.com/questions/70045586/could-not-find-module-system-console-mintty-win32-when-compiling-test-framework
flags:
  mintty:
    Win32-2-13-1: false
